Feature/#169291 move hardcoded data
m3tamorphosis/StockManagement pull request #6
Opened 2023-09-19 11:19 UTC by m3tamorphosis

2023-09-19 15:07 UTC, HarryAmmon requested changes

2023-09-19 15:07 UTC, HarryAmmon commented on StockManagement/Models/Laptop.cs
> -        public Laptop(string name, int stockAmount, decimal? price, decimal screen, int ram, int storage)
Don't really understand why you've removed the constructor. If you find you don't always need to have these properties you can have multiple constructors that accept different parameters. 

You can also add back the default constructor `public Laptop(){ }` which would allow you to assign values to the properties directly `new Laptop{Name = "My name"}`

2023-09-19 15:07 UTC, HarryAmmon commented on StockManagement/Program.cs
> +                        Console.WriteLine($"The total stock of laptops is {_laptopCalc.TotalStock(_laptopRepo)} and the total stock of GPUs is {_gpuCalc.TotalStock(_gpuRepo)}.");
Like with the CRUD class, the calculator class should use dependency injection via the constructor to access the repository

2023-09-19 15:07 UTC, HarryAmmon commented on StockManagement/Repositories/IStockRepository.cs
>          T Update( int? id, T stock);
Why would the ID need to nullable? You would always want the consumer of this class to enter an ID for both `update` and `delete`

2023-09-20 09:34 UTC, m3tamorphosis commented on StockManagement/Program.cs
> +                        Console.WriteLine($"The total stock of laptops is {_laptopCalc.TotalStock(_laptopRepo)} and the total stock of GPUs is {_gpuCalc.TotalStock(_gpuRepo)}.");
Will be done in new branch,
https://dev.azure.com/thepensionsregulator/TPR/_workitems/edit/169538

2023-09-20 14:24 UTC, HarryAmmon requested changes

2023-09-20 14:24 UTC, HarryAmmon commented on StockManagement/Services/SearchLaptop.cs
>              if (String.IsNullOrEmpty(name) == false)
You should always use the lowercase `string` when calling methods on the String class.

`string` is an alias to the `String` class, so whenever we use `string` we are guaranteed to get the original `String` class. There is nothing stopping someone in a nuget package or in this code base to generate a class called `String` which you could end up referencing by accident. Using the alias `string` prevents this from happening

2023-09-20 14:24 UTC, HarryAmmon commented on StockManagement_Test/CRUD_Tests.cs
There should be a separate class for each class you are testing with an appropriate name, normally `ClassnameTests`

2023-09-20 14:24 UTC, HarryAmmon commented on StockManagement_Test/CRUD_Tests.cs
> +            _laptopCalc = new LaptopCalc();
You should only need an instance of the class you are testing. If the class you are testing has a dependency on another class, you should use Moq to mock out an instance of the class

2023-09-21 09:29 UTC, HarryAmmon approved these changes

2023-09-21 09:36 UTC, merged