Feature/#170388 new UI
m3tamorphosis/StockManagement pull request #9
Opened 2023-09-29 12:07 UTC by m3tamorphosis

2023-09-29 12:20 UTC, KyleAlbiston-TPR commented on StockManagement/Program.cs
> +                                Console.WriteLine("Input '1' to update GPUs");
this should be laptop, 
there should also be an option to return to menu

2023-09-29 12:27 UTC, KyleAlbiston-TPR commented on StockManagement/Program.cs
>                      case 4:
There should be a menu option to pick either value or quantity 
there should also be an option to return to menu

2023-09-29 12:55 UTC, KyleAlbiston-TPR commented on StockManagement/Services/Search.cs
Why is this included?

2023-10-02 15:33 UTC, HarryAmmon requested changes

2023-10-02 15:33 UTC, HarryAmmon commented on StockManagement/Services/Search.cs
> +            return null;
It's probably better to return `string.Empty` here instead of `null`. We shouldn't return `null` if we can avoid it.

2023-10-02 15:33 UTC, HarryAmmon commented on StockManagement/Services/Search.cs
> +        public string GetType(int id)
**If** we are going to return `null` we should mark the methods return type as a nullable string

2023-10-02 15:33 UTC, HarryAmmon commented on StockManagement/Services/Search.cs
> +    public class Search
This should implement an interface so we can support Dependency injection and mocking in unit tests

2023-10-02 15:33 UTC, HarryAmmon commented on StockManagement/Services/Search.cs
Would be good to see tests for this

2023-10-02 15:33 UTC, HarryAmmon commented on StockManagement_Test/GPURepository_Tests.cs
You do not need to create a Mock of the class you are testing. You should only mock classes that are dependencies of the class you are testing. The `Add` method should be called on the actual `GPURepository` class

2023-10-02 15:33 UTC, HarryAmmon commented on StockManagement/Services/CRUD_Stock.cs
This class is getting quite big now, if you think back to seperation of concerns, should one class be responsible for dealing with the UI of both laptops and GPUs?

2023-10-03 11:21 UTC, HarryAmmon requested changes

2023-10-03 11:21 UTC, HarryAmmon commented on StockManagement/Services/Search.cs
> +            return String.Empty;
Would be better to use `string.Empty` as this uses the alias and not the reference to the static class directly

2023-10-03 11:21 UTC, HarryAmmon commented on StockManagement_Test/GPURepository_Tests.cs
> +            var GPURepo = new GPURepository();
Creating an instance of the class under test can be done in the `[SetUp]` method with a reference private field. This means you have less code as you don't have to write `var GPURepo = new GPURepo()` in the "Arrange" section of every test

2023-10-05 07:41 UTC, HarryAmmon approved these changes

2023-10-05 08:27 UTC, merged